[Settings]
# Theme
gtk-theme-name=Adwaita-dark
gtk-icon-theme-name=Papirus-Dark
gtk-font-name=JetBrains Mono 11
gtk-cursor-theme-name=Future-cyan-cursors
gtk-cursor-theme-size=24
gtk-application-prefer-dark-theme=1

# Fonts
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintslight
gtk-xft-rgba=rgb

# GTK3 specific
gtk-enable-primary-paste=1
gtk-overlay-scrolling=1
gtk-shell-shows-app-menu=0
gtk-shell-shows-menubar=0
gtk-print-preview-command=evince --preview %f

# Animations
gtk-enable-animations=1
gtk-long-press-time=500

# Decorations
gtk-decoration-layout=menu:close
gtk-titlebar-double-click=iconify
gtk-titlebar-middle-click=none
gtk-titlebar-right-click=menu
