# Global options
[main]
font=JetBrainsMono Nerd Font:size=12
prompt=>
terminal=kitty
lines=12
layer=overlay
width=42
horizontal-pad=20
vertical-pad=12
exit-on-keyboard-focus-loss=true
anchor=center

# Colors
[colors]
background=050a12f0
text=cfefffff
match=00cfffff
selection=4da6ffaa
selection-text=ffffffff
selection-match=ffffffff
border=00cfffff
