# Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12

# Colors
background               #050a12
foreground               #cfefff
selection_background     #00cfff
selection_foreground     #050a12

cursor                   #00cfff
cursor_text_color        #050a12
cursor_shape             beam
cursor_beam_thickness    1.5
cursor_blink_interval    0.5

color0   #050a12
color1   #ff4d4d
color2   #00ffcc
color3   #fff04d
color4   #00cfff
color5   #b266ff
color6   #00e6ff
color7   #d9f6ff

color8   #0b1624
color9   #ff6666
color10  #00ffdd
color11  #fff04d
color12  #33d4ff
color13  #c299ff
color14  #33f0ff
color15  #ffffff

# Borders and paddings
window_padding_width     6
active_border_color      #00cfff
inactive_border_color    #0b1624
bell_border_color        #ffe100
hide_window_decorations  no

# Look
enable_audio_bell        no
visual_bell_duration     0.0
background_opacity       0.92
dynamic_background_opacity yes
