-- hyprland.lua
-- Main configuration entry point

require("configs.monitors")
require("configs.environment")
require("configs.look")
require("configs.autostart")
require("configs.keybinds")

-- Remove the autogenerated warning banner once configured
-- hl.config({ autogenerated = false })