general {
    lock_cmd = hyprlock        
    before_sleep_cmd = hyprlock
}

# 5 mins
listener {
    timeout = 300              
    on-timeout = hyprlock      
}

# 10 mins
listener {
    timeout = 600              
    on-timeout = systemctl suspend
}